### ISSUE TITLE
🚀 [feature]: auto-expand the Results group on failures

### ISSUE THREAD

**Issue by elasticdog** [raven-actions/actionlint#8]
### 🚀 Feature description

Do not have the Results group collapsed by default when a job fails, that way the actual error information is available right away.

### 🔈 Motivation

While the expand feature is great for extra information like the Verbose group, the normal behavior when debugging failures in GitHub Actions (beyond seeing annotations) would be to click on the failing job in the workflow, which automatically expands the failed step and you'll normally see the error directly in the output. Having the Results group collapsed by default makes it less obvious what the issue is, and requires an additional click to get the information you want. The other formatting from `niceHeader` is great though.

### 📜 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by DariuszPorowski** [comment]
@elasticdog makes sense, will try investigating how to auto-expand, because feature is not implemented by GitHub.

initial quick idea: add bool option to the action, like `group-log`, if true - it keeps current behavior, if false - skips grouping and print actionlint result to the log.
Main concept of the action is to use problem-matcher as 1st source of feedback and avoid going to the logs, that's the reason why this is grouped by default.

**Comment by DariuszPorowski** [comment]
@elasticdog example log output, when action input is set: `group-result: false`:

https://github.com/raven-actions/actionlint/actions/runs/5011038961/jobs/8981459202#step:5:374

Is it makes sense?

**Comment by elasticdog** [comment]
👍 That looks perfect! I was very happy to find this action and that it was so polished. Thanks for such a quick response.

**Comment by DariuszPorowski** [comment]
@elasticdog will close PR today and release an update :)
